### ISSUE TITLE
Example fails to start

### ISSUE THREAD

**Issue by doroogle** [setchy/graphql-java-kickstart-federation-example#91]
Cloning the repo and then building (mvn package) followed by running (mvn spring-boot:run) fails to start the application with the following error at the bottom of the stack trace:

`Caused by: graphql.parser.InvalidSyntaxException: Invalid Syntax : offending token '|' at line 22 column 5
`

This happens for both the shows and the reviews projects.

Using mvn 3.6.0, java 18.0.1.1 running on MacOS 12.4.

**Comment by setchy** [comment]
@doroogle - thanks for reporting the above issue.

I've pushed a fix which downgrades com.apollographql.federation:federation-graphql-java-support to the latest version that supported graphql-java:17.x

Until https://github.com/graphql-java-kickstart/graphql-java-tools/issues/664 is resolved, I'm unable to update to a newer versions of graphql-java, kickstart or federation-graphql-java-support
